name: 'Write chengelog'
inputs:
  branch_name:  # id of input
    required: true
    default: 'main'
  commit_message:
    required: true
    default: 'Empty commit message'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Checkout changelog branch
      uses: actions/checkout@v2
      with:
        ref: changelog

    - name: Pull repositiry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git pull

    - name: Get current timestamp
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: -5
        format: 'YYYY-MM-DD-HH-mm-ss'

    - name: Write changelog
      env:
        TIME: "${{ steps.time.outputs.time }}"
      run: |
        echo "## Feature ${{ inputs.branch_name }}" >> CHANGELOG.md
        echo "[ ${{ env.TIME }} ] : deployed on dev <br />" >> CHANGELOG.md
        echo "Last commit message: ${{ inputs.commit_message }}" >> CHANGELOG.md

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated Change
        branch: changelog
        file_pattern: CHANGELOG.md