name: Choose Secret

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Who to greet
        options:
        - monalisa
        - cschleiden

jobs:
  define-cred:
    runs-on: ubuntu-latest
    steps:
      - name: Define credentials
        run: |
          if [[ "${{ github.event.inputs.name }}" == "monalisa" ]];
          then
            echo "Hi monalisa"
          else
            echo "Hi cschleiden"
          fi