name: Choose Secret

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Who to greet
        options:
        - monalisa
        - cschleiden

jobs:
  define-cred:
    runs-on: ubuntu-latest
    steps:
      - name: Define credentials
        run: |
          if [[ "${{ github.event.inputs.name }}" == "monalisa" ]];
          then
            echo "TESTSECRET = creds for ${{ github.event.inputs.name }} is monolisa creds" >> $GITHUB_ENV
          else
            echo "TESTSECRET = creds for ${{ github.event.inputs.name }} is cschleiden creds" >> $GITHUB_ENV
          fi


  check-cred:
    runs-on: ubuntu-latest
    steps:
      - name: See creds
        run: echo ${{ env.TESTSECRET }}