name: Choose Secret

on:
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Who to greet
        options:
        - monalisa

jobs:
  define-cred:
    outputs:
      define-cred-testsecret: ${{ steps.name-id.outputs.TESTSECRET }}
    runs-on: ubuntu-latest
    steps:
      - name: Define credentials
        id: name-id
        run: |
          if [[ "${{ github.event.inputs.name }}" == "monalisa" ]];
          then
            echo "TESTSECRET=creds for ${{ github.event.inputs.name }} is monolisa creds" >> $GITHUB_OUTPUT
          else
            echo "TESTSECRET=creds for ${{ github.event.inputs.name }} is cschleiden creds" >> $GITHUB_OUTPUT
          fi

      - name: Check creds
        run: echo ${{ steps.name-id.outputs.TESTSECRET }}

  check-cred:
    runs-on: ubuntu-latest
    needs: define-cred
    steps:
      - name: Check creds
        run: |
          echo "Credentials is: ${{ needs.define-cred.outputs.define-cred-testsecret }}"