name: STAGE Feature Deployment

on:
  workflow_dispatch

env:
  AWS_REGION: "eu-central-1"
  AWS_S3_PATH_DEV: s3://intergi-duplicate/pageos
  AWS_S3_BUCKET: intergi-duplicate
  DISTRIBUTION_ID: E3MY6RLJJ44XBK
  AWS_ROLE: arn:aws:iam::519140963702:role/TestGithubActionsRole

jobs:
  feature-deploy:
    outputs:
      folder-check: ${{ steps.folder-check.outputs.result }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create a temp package.json
        run: |
          mkdir temp
          cp package.json temp/package.json

      - uses: ./.github/actions/build
        with:
          build-command: 'buildCDN:feature'
          access_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          npm_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN_PACKAGES }}

      - name: Check if the version will be overrided
        id: folder-check
        run: |
          echo "::set-output name=result::$(if [[ $(aws s3 ls ${{ env.AWS_S3_PATH_DEV }}/${{ github.ref_name }}| head) ]]; then echo "overriding"; else echo "new-folder"; fi)"

      - name: Push to bucket
        run: |
          aws s3 sync dist ${{ env.AWS_S3_PATH_DEV }}/${{ github.ref_name }} --acl public-read --delete

      - id: changelog_call
        uses: ./.github/actions/changelog
        with:
          branch_name: ${{ github.ref_name }}
          commit_message: ${{ github.event.head_commit.message }}

      - uses: actions/checkout@v2


  # invalidation:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     id-token: write
  #     contents: read
  #   needs: feature-deploy
  #   if: needs.feature-deploy.outputs.folder-check == 'overriding'

  #   steps:
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         role-to-assume: ${{ env.AWS_ROLE }}
  #         aws-region: ${{ env.AWS_REGION }}

  #     - name: Invalidate CloudFront
  #       uses: chetan/invalidate-cloudfront-action@v2
  #       env:
  #         DISTRIBUTION: ${{ env.DISTRIBUTION_ID }}
  #         PATHS: "/pageos/stage/${{ github.ref_name }}/*"
