name: Invalidation

on:
  workflow_call:
    inputs:
      distribution-id:
        required: true
        type: string
      path:
        required: true
        type: string
      aws-role:
        required: true
        type: string
      aws-region:
        required: true
        type: string
jobs:
  invalidation:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.distribution-id }}
          aws-region: ${{ inputs.aws-region }}

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ inputs.distribution-id }}
          PATHS: ${{ inputs.path }}