name: DEV Deploy prebid

on:
  workflow_dispatch

env:
  AWS_REGION: "eu-central-1"
  AWS_S3_PATH_DEV: s3://intergi-duplicate/pageos-prebid
  AWS_S3_BUCKET: intergi-duplicate
  DISTRIBUTION_ID: E3MY6RLJJ44XBK
  AWS_ROLE: arn:aws:iam::519140963702:role/TestGithubActionsRole

jobs:
  build-deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - run: |
          mkdir temp
          cp package.json temp/package.json

      - uses: ./.github/actions/build
        with:
          build-command: 'buildCDN:dev'
          access_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          npm_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN_PACKAGES }}

      - name: Sort compressed files
        run: |
          mkdir gz br
          cd prebid
          mv *.gz ../gz/
          mv *.br ../br/
          cd ..

      - name: Push to bucket
        run: |
          aws s3 cp prebid ${{ env.AWS_S3_PATH_DEV }} --acl public-read --recursive
          aws s3 cp gz ${{ env.AWS_S3_PATH_DEV }} --acl public-read --recursive --content-encoding gzip --content-type "text/javascript"
          aws s3 cp br ${{ env.AWS_S3_PATH_DEV }} --acl public-read --recursive --content-encoding br --content-type "text/javascript"

      # - name: Invalidate CloudFront
      #   uses: chetan/invalidate-cloudfront-action@v2
      #   env:
      #     DISTRIBUTION: ${{ env.DISTRIBUTION_ID }}
      #     PATHS: "/prebid/*"

      - id: changelog_call
        uses: ./.github/actions/changelog
        with:
          branch_name: ${{ github.ref_name }}
          commit_message: ${{ github.event.head_commit.message }}

      - uses: actions/checkout@v2