name: Deploy prebid

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      s3-path:
        required: true
        type: string
      s3-bucket:
        required: true
        type: string
      distribution-id:
        required: true
        type: string
      aws-role:
        required: true
        type: string

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ inputs.aws-role }}
          aws-region: ${{ inputs.aws-region }}

      - run: |
          mkdir temp
          cp package.json temp/package.json

      - uses: ./.github/actions/build
        with:
          build-command: 'buildCDN:dev'
          access_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}
          npm_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN_PACKAGES }}

      - name: Sort compressed files
        run: |
          mkdir gz br
          cd prebid
          mv *.gz ../gz/
          mv *.br ../br/
          cd ..

      - name: Push to bucket
        run: |
          aws s3 cp prebid ${{ inputs.s3-path }} --acl public-read --recursive
          aws s3 cp gz ${{ inputs.s3-path }} --acl public-read --recursive --content-encoding gzip --content-type "text/javascript"
          aws s3 cp br ${{ inputs.s3-path }} --acl public-read --recursive --content-encoding br --content-type "text/javascript"

      # - name: Invalidate CloudFront
      #   uses: chetan/invalidate-cloudfront-action@v2
      #   env:
      #     DISTRIBUTION: ${{ inputs.dostribution-id }}
      #     PATHS: "/prebid/*"

      - id: changelog_call
        uses: ./.github/actions/changelog
        with:
          branch_name: ${{ github.ref_name }}
          commit_message: ${{ github.event.head_commit.message }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2